'use strict';

module.exports = app => {
  app.get('/a', 'home.index');
  app.get('/', 'home.inde');
  app.get('/sina', 'home.indexx');
  app.get('/test', 'home.test');
  app.get('/Test', 'home.test');
  app.get('/chunk', 'home.chu');
  app.get('/concat', 'home.con');
  app.get('/compact', 'home.cp');
  app.get('/he', 'home.hel');
  app.get('/cat', 'home.c');
  app.get('/dog', 'home.d');
  app.post('/time', 'home.times');
  app.get('/time', 'home.times');
  app.get('/stest', 'home.ste');
  app.post('/heltimes', 'home.heltime');
  app.get('/heltimes', 'home.heltime');
  app.get('/h1', 'home.hel1');
  app.get('/h2', 'home.hel2');
  app.get('/h3', 'home.hel3');
  app.get('/h4', 'home.hel4');
  app.get('/h5', 'home.hel5');
  app.get('/h6', 'home.hel6');
  app.post('/creat', 'mysql.creat');
  app.post('/delete', 'mysql.delet');
  app.post('/update', 'mysql.updat');
  app.post('/get', 'mysql.ge');
  app.post('/screate', 'mysql.screat');
  app.post('/sdelete', 'mysql.sdelet');
  app.post('/supdate', 'mysql.supdat');
  app.post('/sget', 'mysql.sge');
};
